package com.sloth.model.base;

import java.util.HashMap;
import java.util.Map;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {
	private static Map<String, String> mappings;
	static {
		mappings = new HashMap<>();
		mappings.put("id","ID");
		mappings.put("code","CODE");
		mappings.put("desc","DESC");
		mappings.put("name","NAME");
		mappings.put("value","VALUE");
	}
	
	public static String toColumnName(String name) {
		return mappings.get(name);
	}

	public static String getTablename() {
		return "t_config";
	}

	public void setId(java.lang.Integer id) {
		set("ID", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public void setCode(java.lang.String code) {
		set("CODE", code);
	}
	
	public java.lang.String getCode() {
		return getStr("CODE");
	}

	public void setDesc(java.lang.String desc) {
		set("DESC", desc);
	}
	
	public java.lang.String getDesc() {
		return getStr("DESC");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}
	
	public java.lang.String getName() {
		return getStr("NAME");
	}

	public void setValue(java.lang.String value) {
		set("VALUE", value);
	}
	
	public java.lang.String getValue() {
		return getStr("VALUE");
	}

}
