package com.sloth.model.base;

import java.util.HashMap;
import java.util.Map;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {
	private static Map<String, String> mappings;
	static {
		mappings = new HashMap<>();
		mappings.put("id", "ID");
		mappings.put("code", "CODE");
		mappings.put("name", "NAME");
		mappings.put("remark", "REMARK");
		mappings.put("editable", "EDITABLE");
		mappings.put("deletable", "DELETABLE");
		mappings.put("createTime", "CREATE_TIME");
		mappings.put("udpateTime", "UPDATE_TIME");
	}

	public static String toColumnName(String name) {
		return mappings.get(name);
	}

	public static String getTablename() {
		return "t_role";
	}

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return getStr("ID");
	}

	public void setCode(java.lang.String code) {
		set("CODE", code);
	}

	public java.lang.String getCode() {
		return getStr("CODE");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return getStr("NAME");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}

	public java.lang.String getRemark() {
		return getStr("REMARK");
	}

	public void setEditable(java.lang.Integer editable) {
		set("EDITABLE", editable);
	}

	public java.lang.Integer getEditable() {
		return getInt("EDITABLE");
	}

	public void setDeletable(java.lang.Integer deletable) {
		set("DELETABLE", deletable);
	}

	public java.lang.Integer getDeletable() {
		return getInt("DELETABLE");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return getDate("CREATE_TIME");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("UPDATE_TIME", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return getDate("UPDATE_TIME");
	}
}
