package com.sloth.model;

import com.sloth.model.base.BaseRoleUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleUser extends BaseRoleUser<RoleUser> {
	public static final RoleUser dao = new RoleUser().dao();
}
