package com.sloth.model.base;

import java.util.HashMap;
import java.util.Map;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseData<M extends BaseData<M>> extends Model<M> implements IBean {
	private static Map<String, String> mappings;
	static {
		mappings = new HashMap<>();
		mappings.put("id","ID");
		mappings.put("code","CODE");
		mappings.put("name","NAME");
		mappings.put("enableAuth","ENABLE_AUTH");
	}
	
	public static String toColumnName(String name) {
		return mappings.get(name);
	}

	public static String getTablename() {
		return "t_data";
	}

	public void setId(java.lang.String id) {
		set("ID", id);
	}
	
	public java.lang.String getId() {
		return getStr("ID");
	}

	public void setCode(java.lang.String code) {
		set("CODE", code);
	}
	
	public java.lang.String getCode() {
		return getStr("CODE");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}
	
	public java.lang.String getName() {
		return getStr("NAME");
	}

	public void setEnableAuth(java.lang.Integer enableAuth) {
		set("ENABLE_AUTH", enableAuth);
	}
	
	public java.lang.Integer getEnableAuth() {
		return getInt("ENABLE_AUTH");
	}

}
